// Mocks generated by Mockito 5.4.6 from annotations
// in speedlab_admin/test/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:get/get.dart' as _i2;
import 'package:get_storage/get_storage.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:speedlab_admin/app/data/models/user_model.dart' as _i8;
import 'package:speedlab_admin/app/data/providers/bookings_provider.dart'
    as _i4;
import 'package:speedlab_admin/app/data/services/auth_service.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetHttpClient_1 extends _i1.SmartFake implements _i2.GetHttpClient {
  _FakeGetHttpClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSocket_4 extends _i1.SmartFake implements _i2.GetSocket {
  _FakeGetSocket_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGraphQLResponse_5<T1> extends _i1.SmartFake
    implements _i2.GraphQLResponse<T1> {
  _FakeGraphQLResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetStorage_6 extends _i1.SmartFake implements _i3.GetStorage {
  _FakeGetStorage_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxn_7<T> extends _i1.SmartFake implements _i2.Rxn<T> {
  _FakeRxn_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BookingsProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingsProvider extends _i1.Mock implements _i4.BookingsProvider {
  @override
  bool get allowAutoSignedCert =>
      (super.noSuchMethod(
            Invocation.getter(#allowAutoSignedCert),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get userAgent =>
      (super.noSuchMethod(
            Invocation.getter(#userAgent),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#userAgent),
            ),
          )
          as String);

  @override
  bool get sendUserAgent =>
      (super.noSuchMethod(
            Invocation.getter(#sendUserAgent),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  String get defaultContentType =>
      (super.noSuchMethod(
            Invocation.getter(#defaultContentType),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#defaultContentType),
            ),
            returnValueForMissingStub: _i5.dummyValue<String>(
              this,
              Invocation.getter(#defaultContentType),
            ),
          )
          as String);

  @override
  bool get followRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#followRedirects),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get maxRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#maxRedirects),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  int get maxAuthRetries =>
      (super.noSuchMethod(
            Invocation.getter(#maxAuthRetries),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  Duration get timeout =>
      (super.noSuchMethod(
            Invocation.getter(#timeout),
            returnValue: _FakeDuration_0(this, Invocation.getter(#timeout)),
            returnValueForMissingStub: _FakeDuration_0(
              this,
              Invocation.getter(#timeout),
            ),
          )
          as Duration);

  @override
  bool get withCredentials =>
      (super.noSuchMethod(
            Invocation.getter(#withCredentials),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  List<_i2.GetSocket> get sockets =>
      (super.noSuchMethod(
            Invocation.getter(#sockets),
            returnValue: <_i2.GetSocket>[],
            returnValueForMissingStub: <_i2.GetSocket>[],
          )
          as List<_i2.GetSocket>);

  @override
  _i2.GetHttpClient get httpClient =>
      (super.noSuchMethod(
            Invocation.getter(#httpClient),
            returnValue: _FakeGetHttpClient_1(
              this,
              Invocation.getter(#httpClient),
            ),
            returnValueForMissingStub: _FakeGetHttpClient_1(
              this,
              Invocation.getter(#httpClient),
            ),
          )
          as _i2.GetHttpClient);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(
            Invocation.getter(#isDisposed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set allowAutoSignedCert(bool? value) => super.noSuchMethod(
    Invocation.setter(#allowAutoSignedCert, value),
    returnValueForMissingStub: null,
  );

  @override
  set userAgent(String? value) => super.noSuchMethod(
    Invocation.setter(#userAgent, value),
    returnValueForMissingStub: null,
  );

  @override
  set sendUserAgent(bool? value) => super.noSuchMethod(
    Invocation.setter(#sendUserAgent, value),
    returnValueForMissingStub: null,
  );

  @override
  set baseUrl(String? value) => super.noSuchMethod(
    Invocation.setter(#baseUrl, value),
    returnValueForMissingStub: null,
  );

  @override
  set defaultContentType(String? value) => super.noSuchMethod(
    Invocation.setter(#defaultContentType, value),
    returnValueForMissingStub: null,
  );

  @override
  set followRedirects(bool? value) => super.noSuchMethod(
    Invocation.setter(#followRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxRedirects(int? value) => super.noSuchMethod(
    Invocation.setter(#maxRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxAuthRetries(int? value) => super.noSuchMethod(
    Invocation.setter(#maxAuthRetries, value),
    returnValueForMissingStub: null,
  );

  @override
  set defaultDecoder(_i2.Decoder<dynamic>? value) => super.noSuchMethod(
    Invocation.setter(#defaultDecoder, value),
    returnValueForMissingStub: null,
  );

  @override
  set timeout(Duration? value) => super.noSuchMethod(
    Invocation.setter(#timeout, value),
    returnValueForMissingStub: null,
  );

  @override
  set trustedCertificates(List<_i2.TrustedCertificate>? value) =>
      super.noSuchMethod(
        Invocation.setter(#trustedCertificates, value),
        returnValueForMissingStub: null,
      );

  @override
  set findProxy(String Function(Uri)? value) => super.noSuchMethod(
    Invocation.setter(#findProxy, value),
    returnValueForMissingStub: null,
  );

  @override
  set withCredentials(bool? value) => super.noSuchMethod(
    Invocation.setter(#withCredentials, value),
    returnValueForMissingStub: null,
  );

  @override
  set sockets(List<_i2.GetSocket>? value) => super.noSuchMethod(
    Invocation.setter(#sockets, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<_i2.Response<dynamic>> addBooking(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#addBooking, [data]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#addBooking, [data]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#addBooking, [data]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> fetchAllBookings() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllBookings, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#fetchAllBookings, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#fetchAllBookings, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> fetchMyBookings() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyBookings, []),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#fetchMyBookings, []),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#fetchMyBookings, []),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> cancelBooking(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#cancelBooking, [id]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#cancelBooking, [id]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#cancelBooking, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> updateStatusBooking(
    String? id,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateStatusBooking, [id, status]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateStatusBooking, [id, status]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#updateStatusBooking, [id, status]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  _i6.Future<_i2.Response<dynamic>> fetchBookingsByDate(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBookingsByDate, [date]),
            returnValue: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#fetchBookingsByDate, [date]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_3<dynamic>(
                this,
                Invocation.method(#fetchBookingsByDate, [date]),
              ),
            ),
          )
          as _i6.Future<_i2.Response<dynamic>>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<_i2.Response<T>> get<T>(
    String? url, {
    Map<String, String>? headers,
    String? contentType,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [url],
              {
                #headers: headers,
                #contentType: contentType,
                #query: query,
                #decoder: decoder,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #get,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #get,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> post<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url, body],
              {
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #post,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #post,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> put<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url, body],
              {
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #put,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #put,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> patch<T>(
    String? url,
    dynamic body, {
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url, body],
              {
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #patch,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #patch,
                  [url, body],
                  {
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> request<T>(
    String? url,
    String? method, {
    dynamic body,
    String? contentType,
    Map<String, String>? headers,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
    _i2.Progress? uploadProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url, method],
              {
                #body: body,
                #contentType: contentType,
                #headers: headers,
                #query: query,
                #decoder: decoder,
                #uploadProgress: uploadProgress,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #request,
                  [url, method],
                  {
                    #body: body,
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #request,
                  [url, method],
                  {
                    #body: body,
                    #contentType: contentType,
                    #headers: headers,
                    #query: query,
                    #decoder: decoder,
                    #uploadProgress: uploadProgress,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i6.Future<_i2.Response<T>> delete<T>(
    String? url, {
    Map<String, String>? headers,
    String? contentType,
    Map<String, dynamic>? query,
    _i2.Decoder<T>? decoder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {
                #headers: headers,
                #contentType: contentType,
                #query: query,
                #decoder: decoder,
              },
            ),
            returnValue: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.Response<T>>.value(
              _FakeResponse_3<T>(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {
                    #headers: headers,
                    #contentType: contentType,
                    #query: query,
                    #decoder: decoder,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i2.Response<T>>);

  @override
  _i2.GetSocket socket(
    String? url, {
    Duration? ping = const Duration(seconds: 5),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#socket, [url], {#ping: ping}),
            returnValue: _FakeGetSocket_4(
              this,
              Invocation.method(#socket, [url], {#ping: ping}),
            ),
            returnValueForMissingStub: _FakeGetSocket_4(
              this,
              Invocation.method(#socket, [url], {#ping: ping}),
            ),
          )
          as _i2.GetSocket);

  @override
  _i6.Future<_i2.GraphQLResponse<T>> query<T>(
    String? query, {
    String? url,
    Map<String, dynamic>? variables,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [query],
              {#url: url, #variables: variables, #headers: headers},
            ),
            returnValue: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #query,
                  [query],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #query,
                  [query],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.GraphQLResponse<T>>);

  @override
  _i6.Future<_i2.GraphQLResponse<T>> mutation<T>(
    String? mutation, {
    String? url,
    Map<String, dynamic>? variables,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #mutation,
              [mutation],
              {#url: url, #variables: variables, #headers: headers},
            ),
            returnValue: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #mutation,
                  [mutation],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.GraphQLResponse<T>>.value(
              _FakeGraphQLResponse_5<T>(
                this,
                Invocation.method(
                  #mutation,
                  [mutation],
                  {#url: url, #variables: variables, #headers: headers},
                ),
              ),
            ),
          )
          as _i6.Future<_i2.GraphQLResponse<T>>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i7.AuthService {
  @override
  _i3.GetStorage get box =>
      (super.noSuchMethod(
            Invocation.getter(#box),
            returnValue: _FakeGetStorage_6(this, Invocation.getter(#box)),
            returnValueForMissingStub: _FakeGetStorage_6(
              this,
              Invocation.getter(#box),
            ),
          )
          as _i3.GetStorage);

  @override
  _i2.Rxn<_i8.UserModel> get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _FakeRxn_7<_i8.UserModel>(
              this,
              Invocation.getter(#user),
            ),
            returnValueForMissingStub: _FakeRxn_7<_i8.UserModel>(
              this,
              Invocation.getter(#user),
            ),
          )
          as _i2.Rxn<_i8.UserModel>);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set user(_i2.Rxn<_i8.UserModel>? value) => super.noSuchMethod(
    Invocation.setter(#user, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void login(String? token, _i8.UserModel? userModel) => super.noSuchMethod(
    Invocation.method(#login, [token, userModel]),
    returnValueForMissingStub: null,
  );

  @override
  void logout() => super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
